<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up(): void {
  Schema::create('members', function(Blueprint $t){$t->id();$t->string('first_name',100);$t->string('last_name',100);$t->string('phone',20)->unique();$t->date('birth_date');$t->enum('gender',['male','female','other']);$t->string('email')->nullable();$t->timestamps();});
  Schema::create('member_sessions', function(Blueprint $t){$t->id();$t->foreignId('member_id')->constrained()->cascadeOnDelete();$t->string('token',64)->unique();$t->timestamp('expires_at');$t->timestamps();$t->index(['member_id','expires_at']);});
  Schema::create('branches', function(Blueprint $t){$t->id();$t->string('name');$t->text('address')->nullable();$t->string('phone',20)->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('employees', function(Blueprint $t){$t->id();$t->foreignId('branch_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('phone',20)->nullable();$t->string('line_user_id')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('services', function(Blueprint $t){$t->id();$t->string('name');$t->unsignedInteger('duration_minutes');$t->decimal('price',10,2);$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('bookings', function(Blueprint $t){$t->id();$t->string('booking_no',30)->unique();$t->foreignId('member_id')->constrained()->restrictOnDelete();$t->foreignId('branch_id')->constrained()->restrictOnDelete();$t->foreignId('employee_id')->constrained()->restrictOnDelete();$t->foreignId('service_id')->constrained()->restrictOnDelete();$t->date('booking_date');$t->time('start_time');$t->time('end_time');$t->enum('status',['pending','confirmed','checked_in','completed','cancelled','no_show'])->default('confirmed');$t->string('qr_token',64)->unique();$t->timestamp('checked_in_at')->nullable();$t->timestamp('checked_out_at')->nullable();$t->timestamps();$t->index(['employee_id','booking_date','start_time']);$t->index(['branch_id','booking_date']);});
  Schema::create('booking_slots', function(Blueprint $t){$t->id();$t->foreignId('booking_id')->constrained()->cascadeOnDelete();$t->foreignId('employee_id')->constrained()->restrictOnDelete();$t->date('slot_date');$t->time('slot_time');$t->timestamps();$t->unique(['employee_id','slot_date','slot_time']);});
  Schema::create('point_histories', function(Blueprint $t){$t->id();$t->foreignId('member_id')->constrained()->restrictOnDelete();$t->foreignId('booking_id')->nullable()->constrained()->nullOnDelete();$t->enum('type',['earn','redeem','adjust','expire']);$t->integer('points');$t->decimal('sales_amount',10,2)->nullable();$t->string('description')->nullable();$t->timestamps();$t->index(['member_id','created_at']);});
  Schema::create('roles', function(Blueprint $t){$t->id();$t->string('name')->unique();$t->string('display_name');$t->timestamps();});
  Schema::create('permissions', function(Blueprint $t){$t->id();$t->string('name')->unique();$t->string('display_name');$t->timestamps();});
  Schema::create('admins', function(Blueprint $t){$t->id();$t->foreignId('role_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('email')->unique();$t->string('password');$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('permission_role', function(Blueprint $t){$t->foreignId('role_id')->constrained()->cascadeOnDelete();$t->foreignId('permission_id')->constrained()->cascadeOnDelete();$t->primary(['role_id','permission_id']);});
  Schema::create('coupons', function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('name');$t->text('description')->nullable();$t->enum('discount_type',['fixed','percentage']);$t->decimal('discount_value',10,2);$t->date('valid_from');$t->date('valid_until');$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('coupon_usages', function(Blueprint $t){$t->id();$t->foreignId('coupon_id')->constrained()->restrictOnDelete();$t->foreignId('member_id')->constrained()->restrictOnDelete();$t->foreignId('booking_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('confirmed_by_admin_id')->nullable()->constrained('admins')->nullOnDelete();$t->timestamp('used_at')->nullable();$t->timestamps();$t->unique(['coupon_id','member_id','booking_id']);});
  Schema::create('promotions', function(Blueprint $t){$t->id();$t->string('name');$t->text('description')->nullable();$t->date('starts_at');$t->date('ends_at');$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('notification_logs', function(Blueprint $t){$t->id();$t->foreignId('member_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('booking_id')->nullable()->constrained()->nullOnDelete();$t->enum('channel',['line']);$t->enum('type',['booking_confirmation','reminder_24h','reminder_1h','check_out']);$t->string('recipient');$t->text('message');$t->enum('status',['pending','sent','failed'])->default('pending');$t->text('response')->nullable();$t->timestamp('sent_at')->nullable();$t->timestamps();});
  Schema::create('activity_logs', function(Blueprint $t){$t->id();$t->foreignId('admin_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('subject_type')->nullable();$t->unsignedBigInteger('subject_id')->nullable();$t->json('properties')->nullable();$t->ipAddress('ip_address')->nullable();$t->timestamps();$t->index(['subject_type','subject_id']);});
  Schema::create('settings', function(Blueprint $t){$t->id();$t->string('key')->unique();$t->text('value')->nullable();$t->timestamps();});
 }
 public function down(): void { Schema::dropIfExists('settings');Schema::dropIfExists('activity_logs');Schema::dropIfExists('notification_logs');Schema::dropIfExists('promotions');Schema::dropIfExists('coupon_usages');Schema::dropIfExists('coupons');Schema::dropIfExists('point_histories');Schema::dropIfExists('booking_slots');Schema::dropIfExists('bookings');Schema::dropIfExists('permission_role');Schema::dropIfExists('admins');Schema::dropIfExists('permissions');Schema::dropIfExists('roles');Schema::dropIfExists('services');Schema::dropIfExists('employees');Schema::dropIfExists('branches');Schema::dropIfExists('member_sessions');Schema::dropIfExists('members'); }
};
